inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'lib/csv_extraction/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
