service: moiree

image: fightingtheboss/moiree

servers:
  web:
    hosts:
      - 157.90.29.34

proxy:
  ssl:
    certificate_pem: SSL_CERTIFICATE_PEM
    private_key_pem: SSL_PRIVATE_KEY_PEM
  host: moir.ee
  app_port: 3000
  forward_headers: true

registry:
  username: fightingtheboss
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: 3          # CX33 has 4 vCPUs
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY

accessories: {}                 # No separate DB or Redis needed

asset_path: /rails/public/assets

volumes:
  - /opt/moiree/storage:/rails/storage
