# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  backup_db_to_s3:
    class: "BackupDbToS3Job"
    schedule: "every day at 12:00am"
  daily_summary_tweet:
    class: "DailySummaryTweetJob"
    schedule: "every day at 11:50pm"
