default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
#   workers:
#     - queues: "*"
#       threads: 3
#       processes: 1
#       polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
 dispatchers:
  - recurring_tasks:
      backup_db_to_s3:
        class: "BackupDbToS3Job"
        schedule: "every day at 12:00am"
      daily_summary_tweet:
        class: "DailySummaryTweetJob"
        schedule: "every day at 11:50pm"
