# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches-ignore:
      - main
  workflow_call:
    secrets:
      RAILS_MASTER_KEY:
        required: true
env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # - name: Enable corepack
      #   run: |
      #     corepack enable
      #     corepack yarn install
      # - name: Install node, yarn, and dependencies
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.11.1
      #     cache: yarn
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:test:prepare
      - name: Build assets for integration tests
        run: bin/rails test:prepare
      # Add or replace test runners here
      - name: Run tests
        run: bin/rails test

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     #- name: Security audit dependencies
  #     #  run: bin/bundler-audit --update
  #     #- name: Security audit application code
  #     #  run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
